# Generated by Django 2.2.1 on 2019-05-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='tage',
            options={'ordering': ('name',)},
        ),
    ]
