# Generated by Django 2.2.1 on 2019-05-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tage',
            name='name',
        ),
        migrations.AddField(
            model_name='tage',
            name='name',
            field=models.CharField(default='tag1', max_length=200),
        ),
    ]
