# Generated by Django 2.2.1 on 2019-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190511_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tages',
            field=models.ManyToManyField(blank=True, to='projects.Tage'),
        ),
    ]
